### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by k-morozov** [k-morozov/AppChat#6]
Add documentation  - doxygen

**Comment by k-morozov** [comment]
need to add Doxygen, a documentation generator, to the project.

**Comment by asminimulin** [comment]
I've added Doxyfile.
If you want to generate docs you need to install doxygen(and graphviz if you want to see inheritance graphs in docs).
`apt install doxygen`
`apt install graphviz`
After that to actually generate docs you need to run
`doxygen Doxyfile` (Importantly, you need to run it from project root)
As the result you would have folder <project_root>/docs where you can find html folder with docs available from browser.
Next I am going to add some docs to src and create a pull request after that.

**Comment by k-morozov** [comment]
@asminimulin need add new branch with doxygen. also, need add pull request.
make sure that doxygen write in all cmake files.

**Comment by asminimulin** [comment]
@k-morozov I do not see the point why should we duplicate documentation generation inside every subproject because subprojects cannot be compiled standalone because current cmake configuration does not give such opportunity. Probably #37 does not work properly also because of that wrong configured cmake. It would be good to rewrite it following modern cmake guidelines.

**Comment by k-morozov** [comment]
@asminimulin 
problem #37 - installing SQLite on travis. 
`because subprojects cannot be compiled standalone because current cmake configuration does not give such opportunity` - For example, what is the dependence on lib/protocol ?
`It would be good to rewrite it following modern cmake guidelines` - need examples.
